const INVENTORY_CONSTANTS = {
  EXPIRED: 0,
  EXPIRING_THREE_DAYS: 3,
  LOW_STOCK: 1,
  MIN_RESTOCK_DAYS: 7,
  RESTOCK_AMOUNT: 2,
};

const MEAL_CONSTANTS = {
  TOTAL_MEALS: 7,
  MAX_REPEATS: 2,
  MAX_MISSING: 3,
};

module.exports = {
  INVENTORY_CONSTANTS,
  MEAL_CONSTANTS,
};
