const PRIORITY_CONSTANTS = {
  PRIORITY_ONE: 95,
  PRIORITY_TWO: 80,
  PRIORITY_THREE: 65,
  NEUTRAL: 50,
  EXPIRING_PRIORITY_ONE_DAYS: 1,
  EXPIRING_PRIORITY_TWO_DAYS: 3,
  EXPIRING_PRIORITY_THREE_DAYS: 7,
};

const DIETS = {
  VEGAN: "vegan",
  VEGETARIAN: "vegetarian",
  GLUTEN_FREE: "gluten-free",
  KETOGENIC: "ketogenic",
  NONE: "None",
};

const PREP_CONSTANTS = {
  SUCCESS: 100,
  FAILURE: 10,
  NEUTRAL: 70,
};

const PREP_BUCKETS = {
  OVER_MAX: 10,
  BEST_TIME: 15,
  SECOND_BEST: 30,
  THIRD_BEST: 45,
  FOURTH_BEST: 60,
  FIFTH_BEST: 120,
  WORST: 0,
  BEST_SCORE: 100,
  SECOND_SCORE: 85,
  THIRD_SCORE: 60,
  FOURTH_SCORE: 30,
  FIFTH_SCORE: 10,
  WORST: 0,
};

const CUISINE_CONSTANTS = {
  NEUTRAL: 70,
  SUCCESS: 100,
  FAILURE: 20,
};

const INGREDIENT_TYPES = {
  EXACT: "exact",
  PARTIAL: "partial",
};

const NUTRIENT_CONSTANTS = {
  CALORIES: "Calories",
  PROTEIN: "Protein",
  CARBS: "Carbs",
  FAT: "Fat",
};

const MACRO_CONSTANTS = {
  IN_RANGE: 100,
  INVALID: 0,
};

module.exports = {
  PRIORITY_CONSTANTS,
  DIETS,
  PREP_CONSTANTS,
  CUISINE_CONSTANTS,
  INGREDIENT_TYPES,
  NUTRIENT_CONSTANTS,
  MACRO_CONSTANTS,
  PREP_BUCKETS,
};
